=== luunpl/University/Semestre_5/FD-XML/TP/TP4_Trajectoires/XML/Simulator.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:sim="http://www.univ-grenoble-alpes.fr/trajSim"
           targetNamespace="http://www.univ-grenoble-alpes.fr/trajSim"
           elementFormDefault="qualified">

    <xs:include schemaLocation="Environment.xsd"/>

    <xs:element name="simulator" type="sim:Simulator"/>

    <xs:complexType name="Simulator">
        <xs:sequence>
            <xs:element name="simulationInfo" type="sim:SimulationInfo"/>
            <xs:element name="recordInfo" type="sim:RecordInfo"/>
            <xs:element name="timeInfo" type="sim:TimeInfo"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="TimeInfo">
        <xs:sequence>
            <xs:element name="simulationTime" type="xs:unsignedInt"/>
            <xs:element name="recordFrequency" type="xs:unsignedInt"/>
            <xs:element name="displayUpdate" type="xs:unsignedInt"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="SimulationInfo">
        <xs:sequence>
            <xs:element name="classname"/>
            <xs:element name="path"/>
            <xs:element name="filename"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="RecordInfo">
        <xs:sequence>
            <xs:element name="recordType" type="sim:RecordType"/>
            <xs:element name="when" type="sim:WhenToRecord"/>
            <xs:element name="path"/>
            <xs:element name="output" type="sim:Output"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="Output">
        <xs:restriction base="xs:string">
            <xs:enumeration value="XML"/>
            <xs:enumeration value="SVG"/>
            <xs:enumeration value="Both"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="WhenToRecord">
        <xs:restriction base="xs:string">
            <xs:enumeration value="EndOfSimulation"/>
            <xs:enumeration value="Frequency"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="RecordType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Trajectories"/>
            <xs:enumeration value="Positions"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== luunpl/University/Semestre_5/FD-XML/TP/Trajectoires/XML/Simulator.xml
<?xml version="1.0" encoding="UTF-8" ?>
<simulator
        xmlns="http://www.univ-grenoble-alpes.fr/trajSim"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.univ-grenoble-alpes.fr/trajSim Simulator.xsd">
    <simulationInfo>
        <classname>ParticleSimulation_WithoutCollisions</classname>
        <path>./XML/</path>
        <filename>Simulation.xml</filename>
    </simulationInfo>
    <recordInfo>
        <recordType>Trajectories</recordType>
        <when>EndOfSimulation</when>
        <path>./XML/Records/</path>
        <output>SVG</output>
    </recordInfo>
    <timeInfo>
        <simulationTime>100</simulationTime>
        <recordFrequency>5</recordFrequency>
        <displayUpdate>20</displayUpdate>
    </timeInfo>
</simulator>
